### ISSUE TITLE
Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by eferr216** [eferr216/specificPet#1]
@pawaitemadisoncollege project 1 checkpoint is ready for review!

**Comment by pawaitemadisoncollege** [comment]
Hi @eferr216! 

**Problem statement** 

Does a good job clearly explaining the problem and the solution. 

- [x] This line in the readme.md should be removed: "Examples of documentation of progress, reflections, and time spent on this class. Choose a format that works for you, or create your own."

- [x] To help those viewing your repository understand the technology used in the solution, consider including a list of the tech you are using in the readme.md. 

- [x]  I can't recall, did you identify a web service that you will use for this project?  If not, let's explore this.  You could also use  javamail or similar - to notify users when a match is made with their pet request. 

**User stories w/ MVP stories identified** Your users stories are clear and well-written following the best practices for user stories. They clearly communicate what your application will do. Your MVP stories seem to include what's needed for the ent java project requirements like crud, and multiple tables with more than one one-to-many relationship. I think you've done a good job scoping the project to what's doable this semester. If you need to slim anything down, you could reduce the number of search options (pet attributes).

**Wireframes**. Good work on these! The wireframes clearly communicate what each page will do and seem to match up with the user stories above.

- [x] Something to know is that we'll be using AWS cognito for sign up/sign in capability, so there are some screens that you may not have to worry about as they can be provided by Cognito itself.  We'll learn more about this in week 7.

**Project Plan** A good start!

- [x] There's reference to Trails - this should be updated to reflect your project. 

- [x] I recommend at least identifying which user story you plan to work on each week.  You have a good start at this, with "Find Pets by Age" - now continue that for each story in the weeks on your plan. Chatgpt can be helpful brainstorming tasks if you are having trouble coming up with them. I think the more detailed you can be the better. What do you think about creating a task for each story to decide which jsp/s, controllers, entities, tables you'll need for that story.  Revising the plan could be a task on the plan itself (woah!)

**Reflection/Time log** Keep up the good work with this. Document **all** time spent in class, not just time on your indie project. This helps us both evaluate what might need more or less time!

**Other**

- [x] I noticed you are doing your work on the master branch, but the default branch that shows in GitHub is the main branch. It would be best to merge master to main and then use main. This way anyone viewing your repository will see the most current information.

**Status for checkpoint 1: met**

**Complete the items listed above before checkpoint 2.  If you have any questions, please ask!**
